---
- name: docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: docker apt repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install a list of packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-pip
    - python3-docker
    update_cache: yes

- name: Pip install
  pip:
    name: docker-compose

- name: ensure start service dockerd if not started
  ansible.builtin.service:
    name: docker
    state: started

- name: ensure start service containerd if not started
  ansible.builtin.service:
    name: containerd
    state: started

## Post installion steps
- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present

- name: docker ensure group in sudo
  ansible.builtin.user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes

# Docker-compose install
- name: Download docker-compose {{ docker_compose_version }}
  get_url:
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: ~/docker-compose
    mode: '+x'

- name: Check docker-compose exists
  stat: path=~/docker-compose
  register: docker_compose

- name: Move docker-compose to /usr/local/bin/docker-compose
  command: mv ~/docker-compose /usr/local/bin/docker-compose
  when: docker_compose.stat.exists

# Docker-compose up
- name: Copy docker compose files
  copy:
    src: files/{{ item }}
    dest: /{{ item }}
  loop:
  - docker-compose.yaml

- name: Deploy docker compose stack
  docker_compose:
    project_src: /
    files:
    - docker-compose.yaml