---
language: python
services: docker

env:
  global:
    - ROLE_NAME: kubernetes
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10

    - MOLECULE_DISTRO: debian10
      MOLECULE_PLAYBOOK: playbook-calico.yml

install:
  # Install test dependencies.
  - pip install molecule[docker] yamllint ansible-lint docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
