---
- name: docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: docker apt repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install a list of packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes

- name: ensure start service dockerd if not started
  ansible.builtin.service:
    name: docker
    state: started

- name: ensure start service containerd if not started
  ansible.builtin.service:
    name: containerd
    state: started

## Post installion steps
- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present

- name: docker ensure group in sudo
  ansible.builtin.user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes